Header header

bool enabled_vin        # enables or disable vin reporting
bool enable_vref        # enables or disable vref reporting
bool enable_temp        # enables or disable temperature reporting
---
Header header

bool vin_enabled        # shows if vin reporting is enabled
bool vref_enabled       # shows if vref reporting is enabled
bool temp_enabled       # shows if temperature reporting is enabled