Header header

bool ENABLE_VIN = false     # Enables or disable Vin Reporting
bool ENABLE_VREF = false    # Enables or disable Vref Reporting
bool ENABLE_TEMP = false    # Enables or disable Temperature Reporting
---
Header header

bool VIN_ENABLED = false    # Shows if Vin Reporting is enabled
bool VREF_ENABLED = false   # Shows if Vref Reporting is enabled
bool TEMP_ENABLED = false   # Shows if Temperature Reporting is enabled