Header header

uint8 HERTZ_05 = 0        # 0.5 Hz
uint8 HERTZ_02 = 1        # 0.2 Hz
uint8 HERTZ_01 = 2        # 0.1 Hz
uint8 HERTZ_10 = 3        # 1 Hz
uint8 HERTZ_20 = 4        # 2 Hz
uint8 HERTZ_30 = 5        # 3 Hz

uint8 hertz

---
Header header
uint8 hertz